package views;

import javax.swing.JOptionPane;
import dao.ProductoDAO;
import models.Producto;
import tablemodel.ProductoTableModel;

/**
 *
 * @author J. Vidaurre Al.
 */

public class VentanaPrincipal extends javax.swing.JFrame {

    // -----Declaraciones----- //
    
    // DAOs:
    private final dao.ProductoDAO productoDAO = new dao.ProductoDAO();
    private final dao.ProveedorDAO proveedorDAO = new dao.ProveedorDAO();
    private final dao.MovimientoDAO movimientoDAO = new dao.MovimientoDAO();
    
    // TableModels: (no inicializados)
    private tablemodel.ProductoTableModel productoTableModel; // se inicializa al cargar
    private tablemodel.ProveedorTableModel proveedorTableModel;
    private tablemodel.MovimientoTableModel movimientoTableModel;
    
    // -----Fin_Declaraciones----- //
    
    
    // -----Método_Constructor----- //
    
    public VentanaPrincipal() {
        
        initComponents();
        
        // Inicializar tabla vacía y evitar nulls
        productoTableModel = new tablemodel.ProductoTableModel(java.util.Collections.emptyList());
        tblProductos.setModel(productoTableModel);
    }
    
    // -----Fin_Método_Constructor----- //
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnProductos = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnRegistros = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelConexion = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                    Sistema de Gestión de inventario");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnProveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        btnRegistros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistros.setText("Registros");
        btnRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrosActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
            .addComponent(btnRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelConexion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        labelConexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConexion.setText("Conexion: Database");

        labelUser.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUser.setText("User: admin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelConexion)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConexion)
                    .addComponent(labelUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        
        // Carga en background para no bloquear la UI
        new javax.swing.SwingWorker<java.util.List<models.Producto>, Void>() {
            @Override
            protected java.util.List<models.Producto> doInBackground() throws Exception {
                return productoDAO.listar(); // usa tu DAO existente
            }

            @Override
            protected void done() {
                try {
                    java.util.List<models.Producto> lista = get();
                    if (productoTableModel == null) {
                        productoTableModel = new tablemodel.ProductoTableModel(lista);
                        tblProductos.setModel(productoTableModel); // reemplaza con el nombre real
                    } else {
                        productoTableModel.update(lista); // actualiza datos ya mostrados
                    }
                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(VentanaPrincipal.this,
                        "Error cargando productos: " + ex.getMessage(),
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();        
    }//GEN-LAST:event_btnProductosActionPerformed

    
    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        
        new javax.swing.SwingWorker<java.util.List<models.Proveedor>, Void>() {
        @Override
        protected java.util.List<models.Proveedor> doInBackground() {
            return proveedorDAO.listar();
        }
        @Override
        protected void done() {
            try {
                java.util.List<models.Proveedor> lista = get();
                if (proveedorTableModel == null) {
                    proveedorTableModel = new tablemodel.ProveedorTableModel(lista);
                    tblProductos.setModel(proveedorTableModel); // tblProductos es tu JTable
                } else {
                    proveedorTableModel.update(lista);
                }
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(VentanaPrincipal.this,
                    "Error cargando proveedores: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }//GEN-LAST:event_btnProveedoresActionPerformed

    
    private void btnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosActionPerformed
        
        new javax.swing.SwingWorker<java.util.List<models.MovimientoInventario>, Void>() {
        @Override
        protected java.util.List<models.MovimientoInventario> doInBackground() {
            return movimientoDAO.listar();
        }
        @Override
        protected void done() {
            try {
                java.util.List<models.MovimientoInventario> lista = get();
                if (movimientoTableModel == null) {
                    movimientoTableModel = new tablemodel.MovimientoTableModel(lista);
                    tblProductos.setModel(movimientoTableModel);
                } else {
                    movimientoTableModel.update(lista);
                }
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(VentanaPrincipal.this,
                    "Error cargando registros: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }//GEN-LAST:event_btnRegistrosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        // Según el TableModel activo, agregamos el tipo correcto
        var model = tblProductos.getModel();

        /* ----------------------------------------------------------
           AGREGAR PRODUCTO
           ---------------------------------------------------------- */
        if (model instanceof tablemodel.ProductoTableModel) {

            String nombre = JOptionPane.showInputDialog(this, "Nombre del producto:");
            if (nombre == null || nombre.isBlank()) return;

            String precioTxt = JOptionPane.showInputDialog(this, "Precio unitario:");
            if (precioTxt == null || precioTxt.isBlank()) return;

            String stockTxt = JOptionPane.showInputDialog(this, "Stock inicial:");
            if (stockTxt == null || stockTxt.isBlank()) return;

            try {
                java.math.BigDecimal precio = new java.math.BigDecimal(precioTxt);
                int stock = Integer.parseInt(stockTxt);

                models.Producto nuevo = new models.Producto();
                nuevo.setNombre(nombre);
                nuevo.setPrecioUnitario(precio);
                nuevo.setStockActual(stock);

                productoDAO.guardar(nuevo);

                productoTableModel.update(productoDAO.listar());
                JOptionPane.showMessageDialog(this, "Producto agregado.");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
            return;
        }

        /* ----------------------------------------------------------
           AGREGAR PROVEEDOR
           ---------------------------------------------------------- */
        if (model instanceof tablemodel.ProveedorTableModel) {

            String nombre = JOptionPane.showInputDialog(this, "Nombre:");
            if (nombre == null || nombre.isBlank()) return;

            String ruc = JOptionPane.showInputDialog(this, "RUC:");
            if (ruc == null || ruc.isBlank()) return;

            String telefono = JOptionPane.showInputDialog(this, "Teléfono:");
            if (telefono == null) telefono = "";

            try {
                models.Proveedor p = new models.Proveedor();
                p.setNombre(nombre);
                p.setRuc(ruc);
                p.setTelefono(telefono);

                proveedorDAO.guardar(p);

                proveedorTableModel.update(proveedorDAO.listar());
                JOptionPane.showMessageDialog(this, "Proveedor agregado.");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
            return;
        }

        /* ----------------------------------------------------------
           AGREGAR MOVIMIENTO / REGISTRO
           ---------------------------------------------------------- */
        if (model instanceof tablemodel.MovimientoTableModel) {

            String tipo = JOptionPane.showInputDialog(this, "Tipo (entrada/salida):");
            if (tipo == null || tipo.isBlank()) return;

            String cantTxt = JOptionPane.showInputDialog(this, "Cantidad:");
            if (cantTxt == null || cantTxt.isBlank()) return;

            try {
                int cantidad = Integer.parseInt(cantTxt);

                models.MovimientoInventario m = new models.MovimientoInventario();
                m.setTipoMovimiento(tipo);
                m.setCantidad(cantidad);
                m.setFecha(new java.util.Date());

                // usuario fijo (ID = 1)
                models.Usuario u = new models.Usuario();
                u.setIdUsuario(1);
                m.setIdUsuario(u);

                // producto fijo (ID = 1)
                models.Producto p = new models.Producto();
                p.setIdProducto(1);
                m.setIdProducto(p);

                movimientoDAO.guardar(m);

                movimientoTableModel.update(movimientoDAO.listar());
                JOptionPane.showMessageDialog(this, "Registro agregado.");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int row = tblProductos.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento.");
            return;
        }

        var model = tblProductos.getModel();

        /* ----------------------------------------------------------
           ELIMINAR PRODUCTO
           ---------------------------------------------------------- */
        if (model instanceof tablemodel.ProductoTableModel) {

            models.Producto p = productoTableModel.get(row);

            int opt = JOptionPane.showConfirmDialog(this,
                    "¿Eliminar producto: " + p.getNombre() + "?",
                    "Confirmar", JOptionPane.YES_NO_OPTION);

            if (opt != JOptionPane.YES_OPTION) return;

            try {
                productoDAO.eliminar(p.getIdProducto());
                productoTableModel.update(productoDAO.listar());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
            return;
        }

        /* ----------------------------------------------------------
           ELIMINAR PROVEEDOR
           ---------------------------------------------------------- */
        if (model instanceof tablemodel.ProveedorTableModel) {

            models.Proveedor p = proveedorTableModel.get(row);

            int opt = JOptionPane.showConfirmDialog(this,
                    "¿Eliminar proveedor: " + p.getNombre() + "?",
                    "Confirmar", JOptionPane.YES_NO_OPTION);

            if (opt != JOptionPane.YES_OPTION) return;

            try {
                proveedorDAO.eliminar(p);
                proveedorTableModel.update(proveedorDAO.listar());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
            return;
        }

        /* ----------------------------------------------------------
           ELIMINAR MOVIMIENTO / REGISTRO
           ---------------------------------------------------------- */
        if (model instanceof tablemodel.MovimientoTableModel) {

            models.MovimientoInventario m = movimientoTableModel.get(row);

            int opt = JOptionPane.showConfirmDialog(this,
                    "¿Eliminar registro ID: " + m.getIdMovimiento() + "?",
                    "Confirmar", JOptionPane.YES_NO_OPTION);

            if (opt != JOptionPane.YES_OPTION) return;

            try {
                movimientoDAO.eliminar(m);
                movimientoTableModel.update(movimientoDAO.listar());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnRegistros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelConexion;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}